### PR TITLE
WIP: Add loopAttribute to EncodingAttributes

### PR DESCRIPTION
**Pull request by chrysophylax**
See #78

### CODE REVIEW

**Comment by chrysophylax** [comment]
Hmmm. This doesn't seem to jive very well. I must've fessed something up with the order as I'm getting 1 returns from ffmpeg.

**Comment by a-schild** [comment]
I think you must add both as separate arguments like here:
```
if (codec != null)
            {
                ffmpeg.addArgument("-vcodec");
                ffmpeg.addArgument(codec);
            }

```

**Comment by chrysophylax** [comment]
Indeed, that fixed the erroneous return messages. On the other hand, I seem to have entered either an infinite loop or my duration calculation is wrong in my test code where duration = (25 * 1000)

From what I understand, duration as set in EncodingAttributes is supposed to be in milliseconds. Is this correct?

**Comment by a-schild** [comment]
For testing, it might be simpler to get ffmpeg.exe working in the commandline, and then integrating it in jave

**Comment by a-schild** [comment]
Do you mean this https://trac.ffmpeg.org/wiki/Slideshow

**Comment by chrysophylax** [comment]
Yes, the use case was basically for a single image Single image
>
>Example with output video duration set to 30 seconds with -t 30:
>
>ffmpeg -loop 1 -i img.jpg -c:v libx264 -t 30 -pix_fmt yuv420p out.mp4
>

so something similar is the desired output (although I am testing with vp9 and webm and it works, I'm just getting infinitely growing .webm video files :-) )

**Comment by chrysophylax** [comment]
OK, digging into `EncodingAttributes.java` I see it's seconds here 
> Sets the duration (seconds) of the re-encoded stream. 
whereas in MultimediaInfo duration is given as milliseconds which probably confused me ;)

**Comment by chrysophylax** [comment]
So I did what you suggested @a-schild and tested with the included binary.  What I need is basically something like the following exposed. This PR adds the loop attribute but not the -shortest flag.

`./ffmpeg-amd64 -loop 1 -i /tmp/test/image.png -i /tmp/test/audio.ogg -c:v libvpx-vp9 -c:a copy -shortest mux.webm`

**Comment by chrysophylax** [comment]
Seems `-loop 1` is only used for the image demuxer so it must always precede -i ...image.png. Interesting.

**Comment by a-schild** [comment]
Can you please also add some test cases to the project?

See here for some existing test cases.
https://github.com/a-schild/jave2/tree/master/jave-core-test/src/test/java/ws/schild/jave

Just create a new class to test the image->video stuff in different variations.
You can use the existing test images for this or/and add new ones as required

**Comment by a-schild** [comment]
Your merge request is included in the 2.8.0-SNAPSHOT release.
Can you please test it and giveok for a final release if everything is OK?

Thanks for your submission

**Pull request merged**
