### PR TITLE
Feature/custom flags

### PR DESCRIPTION
**Pull request by mressler**
This will address #90 and #93.

I will be going back to the VideoProcessor and related classes to natively handle input format specification and `-safe 0` options.

This is intended to be merged on top of my last pull request.

### CODE REVIEW

**Comment by mressler** [comment]
Added "native" options to EncodingAttributes for inputFormat and safe.

Tests still passing.

Will need to add my test videos to the repo. Do we have a better way of hosting these test videos?

**Comment by a-schild** [comment]
It has a conflict in the jave-core/src/main/java/ws/schild/jave/DefaultFFMPEGLocator.java file, can you please resolve it, then we can merge it

**Comment by a-schild** [comment]
Hosting media files might be option:
https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2

**Comment by mressler** [comment]
All set. Not sure what the conflict was.

**Pull request merged**
