### PR TITLE
Cleaning up some warnings

### PR DESCRIPTION
**Pull request by mressler**
Just cloned the repo and had some warnings. Thought I'd clean them up.

Also migrated some process related code to its own package and renamed it to be more generic.

ProcessLocator can be a functional interface with a default implementation - this opens up the possibility of other companies having their own hierarchy for ProcessLocators.

### CODE REVIEW

**Comment by mressler** [comment]
Can do. I can't tell if there's a naming convention from the branches I can see. I'll go with "planned_3.0.0_changes"?

**Comment by a-schild** [comment]
We dn't have a naming convention for this.
So yes, go with the name you wish

**Comment by a-schild** [comment]
The other changes can be included in the master

**Comment by mressler** [comment]
@a-schild Can you create the branch you'd like me to merge to? As it turns out, I can't create a branch in this repo.

**Comment by a-schild** [comment]
https://github.com/a-schild/jave2/tree/dev-3.0-changes

**Comment by a-schild** [comment]
Can you please also add the @deprecated Annotation in the master for the classes/methods you will remove
And add the new ones also to 2.8.x, so the transition will be smoother for all?

**Pull request merged**
